name: Create Issue

on:
  issues:
    types:
      - opened

jobs:
  create_issue:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install @actions/core

      - name: Validate Issue Inputs
        with:
          issue-number: ${{ github.event.issue.number }}
          issue-body: ${{ github.event.issue.number }}
          issue-title: ${{ github.event.issue.number }}
          issue-labels: ${{ github.event.issue.number }}
        run: node src/validate-input.js
          
