name: Create Issue
on:
  issues:
    types:
      - opened
      - edited
      - reopened

jobs:
  create_issue:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install @actions/core

      - name: Create Issue
        uses: ./src/action.yml
        with:
          data: ${{ toJson(inputs) }}

          
